<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nfg.Store.App\Nfg.Store.App.csproj" />
    <ProjectReference Include="..\..\src\Nfg.Store.Core\Nfg.Store.Core.csproj" />
    <ProjectReference Include="..\..\src\Nfg.Store.Installation\Nfg.Store.Installation.csproj" />
    <ProjectReference Include="..\..\src\Nfg.Store.Platform.Windows\Nfg.Store.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\catalog-v2\**\*">
      <Link>catalog-v2\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
